version: 2.1

jobs:
  build-android:
    docker:
      - image: cimg/android:2023.10  # Use the Android image suitable for your project

    steps:
      - checkout  # Check out the code from your repository
      
      - run:
          name: "Set executable permissions for gradlew"
          command: chmod +x gradlew  # Ensure gradlew is executable

      - run:
          name: "Build the Android project with warnings"
          command: ./gradlew build --warning-mode all  # Build your Android project with warning mode enabled

      - run:
          name: "Run unit tests"
          command: ./gradlew test  # Run unit tests

      - run:
          name: "Run UI tests"
          command: ./gradlew connectedAndroidTest  # Run UI tests on connected devices

workflows:
  build-workflow:
    jobs:
      - build-android

